{
  "openapi": "3.0.0",
  "info": {
    "title": "SAM Agreements",
    "description": "API for exploring agreements.",
    "version": "2.0.0",
    "contact": {
      "name": "Snow Software",
      "url": "https://www.snowsoftware.com"
    }
  },
  "servers": [
    {
      "url": "https://australiasoutheast.snowsoftware.io"
    },
    {
      "url": "https://eastus2.snowsoftware.io"
    },
    {
      "url": "https://westeurope.snowsoftware.io"
    }
  ],
  "tags": [
    {
      "name": "Agreements"
    },
    {
      "name": "Contracts"
    }
  ],
  "paths": {
    "/api/sam/v2/agreements/{id}/periods": {
      "get": {
        "tags": [
          "Agreements"
        ],
        "description": "Returns a collection of periods for a given agreement. You can have multiple periods when one period expires and another is added.",
        "summary": "Get agreement periods",
        "operationId": "periods2",
        "security": [
          {
            "BearerAuth": [
              "sam.agreements.agreement.r"
            ]
          }
        ]
      }
    },
    "/api/sam/v2/agreements": {
      "get": {
        "tags": [
          "Agreements"
        ],
        "description": "Returns a collection of agreements.",
        "summary": "Get agreements",
        "operationId": "agreements",
        "security": [
          {
            "BearerAuth": [
              "sam.agreements.agreement.r"
            ]
          }
        ]
      }
    },
    "/api/sam/v2/agreements/{id}": {
      "get": {
        "tags": [
          "Agreements"
        ],
        "description": "Returns the details of a given agreement.",
        "summary": "Get agreement",
        "operationId": "agreements2",
        "security": [
          {
            "BearerAuth": [
              "sam.agreements.agreement.r"
            ]
          }
        ]
      }
    },
    "/api/sam/v2/agreement-types": {
      "get": {
        "tags": [
          "Agreements"
        ],
        "description": "Returns a collection of agreement types.",
        "summary": "Get agreement types",
        "operationId": "agreement-types",
        "security": [
          {
            "BearerAuth": [
              "sam.agreements.agreement.r"
            ]
          }
        ]
      }
    },
    "/api/sam/v2/agreement-types/{id}": {
      "get": {
        "tags": [
          "Agreements"
        ],
        "description": "Returns the details of a given agreement type.",
        "summary": "Get agreement type",
        "operationId": "agreement-types2",
        "security": [
          {
            "BearerAuth": [
              "sam.agreements.agreement.r"
            ]
          }
        ]
      }
    },
    "/api/sam/v2/contracts/{id}/periods": {
      "get": {
        "tags": [
          "Contracts"
        ],
        "description": "Returns a collection of periods for a given contract.",
        "summary": "Get contract periods",
        "operationId": "periods",
        "security": [
          {
            "BearerAuth": [
              "sam.contracts.contract.r"
            ]
          }
        ]
      }
    },
    "/api/sam/v2/contracts": {
      "get": {
        "tags": [
          "Contracts"
        ],
        "description": "Returns a collection of contracts.",
        "summary": "Get contracts",
        "operationId": "contracts",
        "security": [
          {
            "BearerAuth": [
              "sam.contracts.contract.r"
            ]
          }
        ]
      }
    },
    "/api/sam/v2/contracts/{id}": {
      "get": {
        "tags": [
          "Contracts"
        ],
        "description": "Returns the details of a given contract.",
        "summary": "Get contract",
        "operationId": "contracts2",
        "security": [
          {
            "BearerAuth": [
              "sam.contracts.contract.r"
            ]
          }
        ]
      }
    },
    "/api/sam/v2/contract-types": {
      "get": {
        "tags": [
          "Contracts"
        ],
        "description": "Returns a collection of contract types.",
        "summary": "Get contract types",
        "operationId": "contract-types",
        "security": [
          {
            "BearerAuth": [
              "sam.contracts.contract.r"
            ]
          }
        ]
      }
    },
    "/api/sam/v2/contract-types/{id}": {
      "get": {
        "tags": [
          "Contracts"
        ],
        "description": "Returns the details of a given contract type.",
        "summary": "Get contract type",
        "operationId": "contract-types2",
        "security": [
          {
            "BearerAuth": [
              "sam.contracts.contract.r"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}