name: REST Guidelines Check

on:
  - pull_request

jobs:
  build:
    name: Run Spectral Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ssh-key: ${{ secrets.SSH_READ_ALL }}

      - uses: stoplightio/spectral-action@latest
        with:
          # Validate OpenAPI documents in the "api" directory with the following extensions: "json", "yml", and "yaml".
          file_glob: 'api_specifications/*.{json,yml,yaml}'
          spectral_ruleset: 'api-guidelines/spectral/rest-ruleset.yaml'
